data_url = "https://develop.exnaton.com/api/v2/meterdata/measurement"
auth_url = "https://develop.exnaton.com/api/v2/auth/auth"
rest_api_url = "http://127.0.0.1:5000/"
email = ""
password = ""
credential = {"email" : email, "password" : password}
db_username = ""
db_password = ""
db_host = "127.0.0.1"
db_port = 5432